# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfoGlobo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfoGlobo
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'InfoGloboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InfoGloboUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
